<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>StreamBoard</AssemblyName>
		<RootNamespace>StreamBoard</RootNamespace>
		<ApplicationIcon>Assets\Images\logo.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Assets\Images\banner_background.png" />
		<Resource Include="Assets\Images\Integrations\obs.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Images\Integrations\streamerbot.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Images\Integrations\twitch.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Images\logo.ico">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Images\logo.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
		<PackageReference Include="WPF-UI" Version="4.2.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Core\Styles\" />
	</ItemGroup>
	
</Project>