<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>StreamTabula</AssemblyName>
		<RootNamespace>StreamTabula</RootNamespace>
		<ApplicationIcon>Assets\Images\logo.ico</ApplicationIcon>

		<Version>0.1.1-beta.2</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<Platforms>AnyCPU;x86</Platforms>
		<PublishDir>bin\x86\publish\</PublishDir>
	</PropertyGroup>

	<!-- Assets/Images -->
	<ItemGroup>
		<Resource Include="Assets\Images\banner_background.png" />
		<Resource Include="Assets\Images\Integrations\obs.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Images\Integrations\streamerbot.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Images\Integrations\twitch.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Images\logo.ico">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>		
	</ItemGroup>

	<!-- Assets/Sounds -->
	<ItemGroup>
		<Content Include="Assets\Sounds\shutter.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Sounds\tick.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<!-- Library -->
	<ItemGroup>
		<PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="QRCoder" Version="1.8.0" />
		<PackageReference Include="WPF-UI" Version="4.2.0" />
		<PackageReference Include="obs-websocket-dotnet" Version="5.0.1" />
		<PackageReference Include="NuGet.Versioning" Version="7.3.1" />

		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<!-- Custom Library -->
	<ItemGroup>
		<Reference Include="CustomDragDropLib">
			<HintPath>Libs\CustomDragDropLib.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Watch Include="**\*.xaml" />
	</ItemGroup>

	<!-- wwwroot -->
	<ItemGroup>
		<Content Include="wwwroot\favicon.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="wwwroot\integrations\twitch\script.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="wwwroot\integrations\twitch\style.css">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="wwwroot\integrations\twitch\twitch_auth.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>


</Project>
